### ISSUE TITLE
The yapf-pycharm did not work

### ISSUE THREAD

**Issue by widiot** [binh-vu/yapf-pycharm#4]
I installed and enabled the yapf-pycharm, then formated the code, but it looked like nothing changed,  PyCharm still used the default code style. Are there any settings ?

**Comment by thomasmansencal** [comment]
Is your code valid? Have you tried running Yapf manually in a shell?

**Comment by widiot** [comment]
Yes. I could use command "yapf -i filename" in the terminal to format my source files. Does PyCharm have any settings can override the Yapf?

**Comment by binh-vu** [comment]
Do you invoke yapf using keyboard shortcut? I used to have an issue that it invokes default pycharm formatter but yapf.

Or it can be that there is an error when the plugin tries to call yapf. Make sure that you can call yapf via: /usr/local/bin/yapf.

**Comment by widiot** [comment]
I used keyboard shortcut "control+shift+f" to format my code. I can call yapf via:/usr/local/bin/yapf. Can I view a file to see the call logs?

**Comment by widiot** [comment]
Oh my god! I finally got it.

It was because of  the yapf-pycache has its own keyboard shortcut, in my settings it was "meta+shift+l", but I used "control+shift+f" which is pycharm's default format shortcut.

I'm so stupid. I'm sorry to disturb you. Thank you for answering my question
