### ISSUE TITLE
yapf pycharm only supports Linux.

### ISSUE THREAD

**Issue by LexiconCode** [binh-vu/yapf-pycharm#7]
It would be helpful if you mentioned that in the documentation.

> YAPF must be pre-installed and could be invoked using sh -c /usr/local/bin/yapf command

and

`    private byte[] reformatFile(String path) throws InterruptedException, IOException {
        Process p = Runtime.getRuntime().exec(new String[]{
        "sh", "-c", String.format("/usr/local/bin/yapf '%s'", path)`

The issues described. https://github.com/binh-vu/yapf-pycharm/issues/5

**Comment by sivaswami** [comment]
Please help with Windows support also.
if yapf in path execute it.
